// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmpevmqotiiqpjgfybmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tcGV2bXFvdGlpcXBqZ2Z5Ym1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjc1MjYsImV4cCI6MjA2MjcwMzUyNn0.To93K40uw0Es1GaZG_N52sNVgjBsCFuBB2yE1XAQZVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);